name: review_flutter
description: Review flutter project

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  pull_to_refresh: ^2.0.0
  dio: ^5.2.1
  flutter_dotenv: ^5.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

  flutter_lints: ^2.0.0
  test: ^1.24.1

flutter:
  uses-material-design: true
  assets:
    - .env

fonts:
  - family: Satoshi
    fonts:
      - asset: fonts/Satoshi-Medium.otf
        weight: 500
      - asset: fonts/Satoshi-Bold.otf
        weight: 700

flutter_intl:
  enabled: true
